export const coffeeapi = [
    {
        id: 1,
        title: "Traditional Coffee",
        description: "Espresso is a coffee prepared by forcing hot water through finely-ground coffee beans. It is known for its robust flavour and bold, concentrated taste",
        image: "../public/image/p1.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 9,
        rating: "4.9",
        
    },
    {
        id: 2,
        title: "Lattle Coffee",
        description: "A latte is a coffee figured up with espresso and steamed milk, topped with a thin layer of milk foam. It is typically served in a tall, 12-ounce",
        image: "../public/image/p2.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 11,
        rating: "4.9",
        
    },
    {
        id: 3,
        title: "Heart Coffee",
        description: "Heart is a coffee made with a latte base and chocolate syrup or cocoa powder added. It is typically served in a tall, 12-ounce (360-millilitre) glass.",
        image: "../public/image/p3.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 16,
        rating: "4.9",
        
    },
    {
        id: 4,
        title: "Americano Coffee",
        description: "The Americano is another popular type of coffee drink, and it's very easy to make! It's just espresso with hot water dripping over it.",
        image: "../public/image/p4.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 10,
        rating: "4.9",
        
    },
    {
        id: 5,
        title: "Family Coffee",
        description: "Family Coffee to café lattes, cappuccinos are made with a shot of espresso and milk with significantly more foam which gives it",
        image: "../public/image/p5.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 13,
        rating: "4.9",
        
    },
    {
        id: 6,
        title: "Loved Coffee",
        description: "A Love is a robust and bold coffee ideal for those who need a caffeine boost to get through the day. A doppio is typically served in a small, 4-ounce",
        image: "../public/image/p6.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 17,
        rating: "4.9",
        
    },
    {
        id: 7,
        title: "Couple Coffee",
        description: "A Couple Coffee The word means spotted, so a macchiato espresso is an espresso with a splash of milk",
        image: "../public/image/p7.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 9,
        rating: "4.9",
        
    },
    {
        id: 8,
        title: "cappuccino Coffee",
        description: "A Cappuccino is the perfect balance of espresso, steamed milk and foam. Keep reading to know Cappuccino origins and how to make cappuccino coffee at home.",
        image: "../public/image/p8.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 21,
        rating: "4.9",
        
    },
    {
        id: 9,
        title: "Arabica Coffee",
        description: "Arabica is the most popular and widely used Coffee bean. ",
        image: "../public/image/p9.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 15,
        rating: "4.9",
        
    },
    {
        id: 10,
        title: "Robusta Coffee",
        description: "Also known as “the outcast,” robusta is entirely different from arabica. ",
        image: "../public/image/p10.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 11,
        rating: "4.9",
        
    },
    {
        id: 11,
        title: "Latte Coffee",
        description: "Latte derives its roots from the Italian land. The word Latte means ‘milk Coffee’ in Italy.",
        image: "../public/image/p11.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 13,
        rating: "4.9",
        
    },
    {
        id: 12,
        title: "Frappuccino Coffee",
        description: "Another popularly known drink is Frappuccino. Although its origin is an accidental one, today, Starbucks owns the trademarks for Frappuccino. ",
        image: "../public/image/p12.jpg",
        qty: 10,
        category: "Coffee",
        brand: "Binzay",
        price: 17,
        rating: "4.9",
        
    },
]